### ISSUE TITLE
[Home] - Responsividade da Home

### ISSUE THREAD

**Issue by katsumidev** [SouJunior/vagas-webapp#207]
US Relacionada - https://github.com/SouJunior/products/issues/282

### Descrição:
Essa task tem como objetivo implementar a responsividade da página principal (Home), Essa responsividade visa garantir uma experiência de usuário consistente e de qualidade em diferentes dispositivos e tamanhos de tela.

___

### Subtasks

- [x] Adaptação do header para a versão mobile, no modelo de um menu hamburguer que quando clicado abrirá um menu com as opções do header.
- [x] Aplicar os ajustes necessários para que os elementos sejam redimensionados, reorganizados ou reestilizados adequadamente, garantindo a usabilidade e a legibilidade.
- [x] Testar a página em diferentes tamanhos de tela, visando garantir que não há nenhuma incompatibilidade em nenhum dispositivo
- [x] Fazer ajustes adicionais, se necessário, para garantir uma experiência de usuário suave e consistente em todas as resoluções de tela.

___

### Critérios de aceitação

- [x] Os elementos da página home devem ser ajustados de forma responsiva, de acordo com os diferentes tamanhos de tela.
- [x] Os elementos são redimensionados, reorganizados ou reestilizados de forma apropriada para garantir a legibilidade e a usabilidade em dispositivos móveis e outros tamanhos de tela.
- [x] As página home deve ser testada em diferentes dispositivos e tamanhos de tela para verificar se a responsividade está corretamente implementada.
- [x] A responsividade é verificada em diferentes orientações de tela, como retrato e paisagem, garantindo uma experiência consistente em todas as situações.
- [x] A implementação segue as diretrizes de design responsivo definidas para o aplicativo.

**Comment by caiquefonseca** [comment]
@mooncoded , você consegue colocar a URL desta Task aqui para que o Paulo possa realizar os testes?

**Comment by mooncoded** [comment]
Segue o link 👉 https://vagas-front-end.netlify.app/

**Comment by caiquefonseca** [comment]
@Paru369 , você conseguiria avaliar essa Task, por favor?

**Comment by natamartins** [comment]
Olá colega tudo joia! Cara estou querendo contribuir com algns projetos

**Comment by Paru369** [comment]
Realizei testes exploratórios, testei a responsividade em celulares(357 x 668) e maiores.
Testei a responsividade em tablets. Testado em orientações de restrato e paisagem.

Esta tudo ok, só estou **aguardando ter acesso ao figma** para dar uma olhada no layout e implementação, mas em relação aos itens que estão renderizados não houve nenhuma quebra.

Nas telas em mobile, os itens do menu estão sem ação, mas creio que também não fazem parte dessa entrega.

A pagina de busca de vagas retorna alguns erros 400 mas creio que esta mocada e não faz parte desta entrega.

**Comment by FilipeLeoni** [comment]
Link do protótipo no figma: https://www.figma.com/file/ckOTqIDiOR1oulZd5qUxVD/Projeto%3A-Aplica%C3%A7%C3%A3o?type=design&node-id=73-130&mode=design&t=Es85rx2U5OrMlAfn-0

**Comment by Paru369** [comment]
@FilipeLeoni  Solicitei acesso novamente. Não consigo ver.
![image](https://github.com/SouJunior/vagas-frontend/assets/99094718/c8ed1b98-8068-4de6-8182-defc72b2e5a5)


Vou liberar a feature pois os critérios de aceitação apenas citam a responsidade. 

Quando formos ter homologação de UI dou uma nova olhada.

**Comment by FilipeLeoni** [comment]
Me passa seu email que eu falo com o pessoal de ux para te dar o acesso

**Comment by Paru369** [comment]
> Me passa seu email que eu falo com o pessoal de ux para te dar o acesso

paruvitu@gmail.com

**Comment by FilipeLeoni** [comment]
> > Me passa seu email que eu falo com o pessoal de ux para te dar o acesso
> 
> [paruvitu@gmail.com](mailto:paruvitu@gmail.com)

Acredito que agora está liberado

**Comment by Paru369** [comment]
@FilipeLeoni .

Só uns detalhe em relação ao menu da versão mobile.

Menu:
https://jam.dev/c/1c32d2dd-db2a-45f4-92c1-8fd62fb0af9d

Footer:
https://jam.dev/c/30816a6d-d183-4286-a561-e6bba8efd468

@caiquefonseca eu tinha avançado a task, vê com o time se vão tratar como bug ou rework.

**Comment by caiquefonseca** [comment]
@mooncoded , consegue fazer os ajustes e sinalizar pra gente quando terminar?

**Comment by mooncoded** [comment]
Claro, vou dar uma olhada!

**Comment by mooncoded** [comment]
Pronto, mandei o PR com as mudanças requisitadas

**Comment by caiquefonseca** [comment]
Obrigado, @mooncoded . Quando aprovarem o merge é só marcar o Paru aqui.

**Comment by caiquefonseca** [comment]
@mooncoded , você tá precisando de ajuda com alguma coisa nessa Task?

**Comment by mooncoded** [comment]
@Paru369 @caiquefonseca  Já aprovaram o PR, tinha esquecido de marcar aqui

**Comment by BeatrizFFranco** [comment]
Apontamento 1 - onde está escrito "feed de vagas" deve constar a foto do perfil da pessoa em formato redondo.
Apontamento 2 - tem uma seta no meio do nome da SouJunior, a seta tem que ser retirada.
Apontamento 3 - O nome da SouJunior deve estar centralizado e faltou aparecer uma imagem com 3 barrinhas no canto esquerdo superior que representaria o botão das opções.
Apontamento 4 - no tamanho do quadrado azul, ele não está preenchendo os espaços nas laterais por completo e as margens estão brancas, o certo é ele preencher por completo os espaços nas laterais.
Apontamento 5 - possui um campo de "quando postada" esse campo não tem na US. 


![Image](https://github.com/SouJunior/vagas-frontend/assets/62288579/2e1d7eb6-3905-4302-8260-5780a9c4cbfb)

@mooncoded

**Comment by caiquefonseca** [comment]
@mooncoded , você revisar estes itens indicados pela Beatriz, por favor?

**Comment by caiquefonseca** [comment]
@mooncoded , por favor, atualiza a gente aqui sobre esta task.

**Comment by mooncoded** [comment]
@caiquefonseca @BeatrizFFranco  Só esperando o PR ser aprovado, esses erros pareciam não existir, pois acredito que a Beatriz estava visualizando um deploy antigo, o headero filipe me disse que era provisório, mas em todo caso já alterei de modo que acredito estar correto

esse deploy já contem a versão atualizada 👉deploy-preview-226--vagas-front-end.netlify.app/jobs

**Comment by FernandoMiguelS** [comment]
Boa noite, o PR já foi aprovado para realizarmos os testes? Estou com uma Task onde os erros apontados pela Beatriz sobre a responsividade do feed de vagas precisa ser testado. 

@caiquefonseca 
@mooncoded

**Comment by caiquefonseca** [comment]
A responsividade está incluída na V1 da Home, aguardando aprovação da PR para liberação para teste.

**Comment by FernandoMiguelS** [comment]
Boa noite,  testes realizados, onde foram encontradas diversas inconsistências. Necessitando ajustes. 


[Evidencia_Task_207_.pdf](https://github.com/SouJunior/vagas-frontend/files/12543894/Evidencia_Task_207_.pdf)


@caiquefonseca

**Comment by caiquefonseca** [comment]
Ajustes realizados por @herculesmachado de acordo a solicitação de @FernandoMiguelS . Aguardando novos testes.

**Comment by caiquefonseca** [comment]
@Kaleber-chaves , você consegue fazer os testes dessa US seguindo o mesmo padrão do que fizemos com a US Home?

**Comment by valtertxba** [comment]
**Descrição:** Verificar a responsividade da página principal (Home)
Subtasks:
-  Os elementos da página home devem ser ajustados de forma responsiva, de acordo com os diferentes tamanhos de tela.
- Os elementos são redimensionados, reorganizados ou reestilizados de forma apropriada para garantir a legibilidade e a usabilidade em dispositivos móveis e outros tamanhos de tela.
-  As página home deve ser testada em diferentes dispositivos e tamanhos de tela para verificar se a responsividade está corretamente implementada.
- A responsividade é verificada em diferentes orientações de tela, como retrato e paisagem, garantindo uma experiência consistente em todas as situações.
- A implementação segue as diretrizes de design responsivo definidas para o aplicativo.

**TF01 -** Verificar se a pagina se ajusta de forma responsiva de acordo com diferentes tamanhos de teste:
**Status:** Não Passou
**Evidencias:**

**teste vocacional quebra quando diminui o tamanho da tela, impossibilitando a leitura.**
![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/627cea26-7b09-4832-a08d-ac01ac324d4e)





**Vamos junto nessa jornada, os textos do lado esquerdo é quebrado.**
![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/70e55b64-ae0b-4349-9506-12e054d27a31)


**TF02 -** Testar em diferentes dispositivos e tamanhos, teste modo retrato e paisagem.
**Status:** Não Passou
**Evidencias:**


![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/9852e8a3-4093-4c5a-9385-f3cbbf48bb9f)



![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/331eefe8-54b3-44c9-b7cd-118b61835ea4)



![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/f06ab3b0-4593-472b-bbb3-a795a38c6926)



![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/81bf68dd-2e88-48a6-a86f-c26de9db9246)

**Resultado:** Tanto no navegador com tamanho reduzido ou modo dispositivo e com tamanho personalizados a pagina não ficou completamente responsiva.

@jjsalim @pm-marcelocarvalho @CamilaRoch

**Comment by valtertxba** [comment]
1. **Na versao mobile com a resoluçao 320x675**  o icone da logo desaparece.
2. Mais abaixo da pagina  secao **''Vamos junstos nesta joarnada"**  responsivida ficou ok, porem**um pouco mais abaixo** quebrou um **detalhe no retangulo** em volta dos depoimentos.

![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/7af33c33-bb65-49a4-beda-128938596724)
![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/ae07585a-a87d-423b-bf5f-41928f27a1da)

Em outros modelos de dispositivos moveis, apresentou alguns erros de responsividade na parte como mostra abaixo:
usei como exemplo o iphone xr.


![Image](https://github.com/SouJunior/vagas-webapp/assets/125107825/5d89265e-4c4c-48bc-befb-cd7840be6a5d)
@CamilaRoch @jjsalim @pm-marcelocarvalho

**Comment by alnogueirati** [comment]
segue link com análise dos testes realizados, esta demanda foi reprovado parcialmente pois há alguns ajustes que precisam ser realizados conforme demonstrados no arquivo no link:

https://docs.google.com/document/d/e/2PACX-1vQhpWgOpikSMVTlr33gplq1Eg5I0kNl9mc9Nt7zZIIEJyFCEP-vknUQE8u28konyZebbZ65EWOaOHhZ/pub
